name: Generate Pacman contribution graph

on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create output directory
        run: mkdir -p output
      - uses: Platane/snk@v3
        with:
          github_user_name: Atiq-5
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg
      - name: Commit files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate Pacman graph"
          add: "output/*.svg"
